
[functions.helcim-payment-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/helcim-payment-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/helcim-payment-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/helcim-payment-webhook/*.html" ]

[functions.helcim-confirm]
enabled = true
verify_jwt = true
import_map = "./functions/helcim-confirm/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/helcim-confirm/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/helcim-confirm/*.html" ]
